# 1
on:
  # 2
  push:
    branches: [ "main" ,"devSudarshan"]
  pull_request:
    branches: [ "devSudarshan" ]

  # 3
  # workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest
#     runs-on: macos-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      # 10   
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.7.3"
          channel: 'stable'
          cache: true  

        
      # 12
      # - name: Get dependencies
        # run: flutter pub get
      # - name: Build APK
      #   run: flutter build apk --release
      #   # run: |
      #   #   flutter build ios --no-codesign
      #   #   cd build/ios/iphoneos
      #   #   mkdir Payload
      #   #   ln -S ../Runner.app
      #   #   cd ..
      #   #   zip -r app.ipa Payload

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.TOKEN}}
      
      # Runs a set of commands using the runners shell
      # - name: Start release build
      #   run: flutter build appbundle

      # - name: Get Today Date
      #   id: date
      #   run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      # - name: Get Packages
      #   run: flutter pub get
      # - name: Fix Issue for tflite
      #   run: sed -i 's/compile /implementation /' /opt/hostedtoolcache/flutter/stable-3.7.3-x64/.pub-cache/hosted/pub.dev/tflite-1.1.2/android/build.gradle

      # - name: Build Apk
      #   run: flutter build apk --debug
      
      
      # - name: Archive Files
      #   run: |
      #     sudo apt-get install zip
      #     zip -r archive.zip *

      #  UPLOAD TO DRIVE FOLDER 
          
      # - name: Upload to gdrive
      #   uses: adityak74/google-drive-upload-git-action@main
      #   with:
      #     credentials: ${{secrets.DRIVE_SECRETS}}
      #     filename: "build/app/outputs/apk/debug/app-debug.apk"
      #     folderId: "1JySJu1MsnU_U_iMuS9et0UPbKjvrOi6O"
      #     name: Assesment.v1.0.${{github.run_number}}-${{steps.date.outputs.date}}.apk #"documentation.zip" # optional string
      #     overwrite: "true" # optional boolean
      #     mimeType: "application/vnd.android.package-archive"
    # Send Email
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with: 
          server_address: smtp.gmail.com
    # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USER_EMAIL}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_USER_PASSWORD}}

          subject: Github Actions job result
      # Required recipients' addresses: user@example, user2#example.com
          to: 
          # Required sender full name (address can be skipped):
          from: ${{secrets.FROM}} # <user@example.com>
          # Optional plain body:
          body: Build job of completed successfully This is from GitHub actions. Link to apk https://drive.google.com/drive/folders/1JySJu1MsnU_U_iMuS9et0UPbKjvrOi6O?usp=share_link!
          # Optional HTML body read from file:
          html_body:  " Build job of completed successfully! This is from GitHub actions. Link to apk   https://drive.google.com/drive/folders/1JySJu1MsnU_U_iMuS9et0UPbKjvrOi6O?usp=share_link"
      # Required mail subject:
          # Server port, default 25: